server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # リクエストされたファイルがあればそれを返し、なければ index.html を返す（SPA用設定）
        try_files $uri $uri/ /index.html;
    }
}